### ISSUE TITLE
Ensure project works locally

### ISSUE THREAD

**Issue by Exino329** [WanderPals/WanderPals#10]
Make sure everyone has the common project running locally.

**Comment by mtv47** [comment]
Works on my computer completely with full functionality

**Comment by Exino329** [comment]
Works also on my computer

**Comment by ForestDope** [comment]
Works on my end

**Comment by tosigame** [comment]
works on my machine

**Comment by AgeX21** [comment]
Works on my machine

**Comment by annhit29** [comment]
+1
