### ISSUE TITLE
Figma Wireflows (Members List and Notifications)

### ISSUE THREAD

**Issue by tosigame** [WanderPals/WanderPals#157]
Create User flows for current sprint : 

Notifications and Members list wireflows

**Comment by ForestDope** [comment]
![Image](https://github.com/WanderPals/WanderPals/assets/75079236/fe5ca514-c8f1-4814-8a31-8176095383e9)



![Image](https://github.com/WanderPals/WanderPals/assets/75079236/05def6e4-fd03-47c3-b147-384faca878a3)



![Image](https://github.com/WanderPals/WanderPals/assets/75079236/f0450b51-9977-429e-b473-2aa335b95392)
