### ISSUE TITLE
Display Annoucement in notification screen

### ISSUE THREAD

**Issue by tosigame** [WanderPals/WanderPals#182]
The goal of this issue is to create the view of the annoucement that can be only made by admins/owner.
In the notification screen, the annoucement will be displayed separatly from the notifications.
An annoucement will contain a title and the name of who made the annoucement and the date.
A button to allow creating a new annoucement has to be available only if the current user is an admin/owner.
This issue is focused on the UI part. Logic part will be done in sprint #5

**Comment by Exino329** [comment]
this issue has been adjusted for the same reasons as issue #153.
