### ISSUE TITLE
Architecture Diagram

### ISSUE THREAD

**Issue by mtv47** [WanderPals/WanderPals#74]
* Overall architecture of your application
* Relations between its different screens, data sources, internal state, etc.

**Comment by tosigame** [comment]
![WanderPalsArchitectureDiagram2 drawio](https://github.com/WanderPals/WanderPals/assets/47075878/9363f2b5-83da-4575-9e5a-aba20d222bdf)

**Comment by tosigame** [comment]
![WanderPalsArchitectureDiagramv3 drawio](https://github.com/WanderPals/WanderPals/assets/47075878/b7e76c48-c335-4552-adb8-70040551a145)

**Comment by tosigame** [comment]
V2

**Comment by mtv47** [comment]
Great work!, still work in progress since missing some viewmodels like AgendaViewModel, not a problem and will be filled along the way until Milestone 1
