### ISSUE TITLE
Invite other users functionality / group creation

### ISSUE THREAD

**Issue by mtv47** [WanderPals/WanderPals#81]
Invites fellow travelers via email or app username, which creates a group linked to that specifc trip. Invites implementation is to be determined based on what type of inviting method is feasible to be done for Milestone 1

**Comment by mtv47** [comment]
I've helped with struggles along the way, with invites that weren't registering because of the runBlocking that wasn't happening. But didn't contribute much, will look into adding a Link system to share directly instead of copy pasting the tripId

**Comment by Exino329** [comment]
Note that in this issue, only the feature of joining a trip has been done. The possibility to invite users by sending them the code and allowing them to join has been implemented in issue #109
